### ISSUE TITLE
Display initialization failure after successful installation

### ISSUE THREAD

**Issue by gaohaohoa** [LBC-LNBio/parKVFinder-win#4]
Install according to the description. Although the installation is successful, initialization failure will be displayed
detail:
expected an indented block after 'else' statement on line 411 (__init__.py, line 412)
Unable to initialize plugin 'PyMOL2-parKVFinder-Tools' (pmg_tk.startup.PyMOL2-parKVFinder-Tools).

**Comment by gaohaohoa** [comment]
Is it because of version incompatibility? I am using version 3.0.3

**Comment by jvsguerra** [comment]
Hi @gaohaohoa,

The PyMOL2 parKVFinder Tools were initially developed for PyMOL v2, and I haven’t tested it with PyMOL v3 yet. I’ll take a look at the new version and try to debug the issue.

In the meantime, if possible, please try downgrading PyMOL to version 2.

**Comment by jvsguerra** [comment]
As an alternative, we have released a web version of parKVFinder (v1.2.0) called KVFinder-web, featuring depth and hydropathy characterization. You can access it at https://kvfinder-web.cnpem.br/. For more details, refer to the corresponding article: https://academic.oup.com/nar/article/51/W1/W289/7151338.

**Comment by jvsguerra** [comment]
I attempted to replicate your error on Windows, but I didn’t encounter any issues. Could you please share the exact error message you're receiving? That will help me better understand the problem.

Here’s how I installed PyMOL v3.0.4 via Anaconda:

1. Install [Anaconda](https://www.anaconda.com/download) and make sure to include Anaconda in your PATH during installation.

2. Install [PyMOL](https://www.pymol.org/) via Anaconda by running the following commands in the Command Prompt:

```cmd
conda create -n pymol
conda activate pymol
conda install -c conda-forge -c schrodinger pymol-bundle
```

4. Open PyMOL v3.0.4.

To use PyMOL, activate the pymol environment in Anaconda by running:

```cmd
conda activate pymol
```

Once the environment is activated, you can launch PyMOL by typing:

```cmd
pymol
```

5. Install PyMOL2 parKVFinder Tools
- Download the latest version of PyMOL2-parKVFinder-Tools.zip from [this link](https://github.com/LBC-LNBio/parKVFinder-win/releases/latest/download/PyMOL2-parKVFinder-Tools.zip).
- Open PyMOL, go to **Plugin** menu, click on **Plugin Manager**.
- In the **Plugin Manager** window, go to the **Install New Plugin** tab.
- Under **Install from local file** panel, click **Choose file...**.
- In the**Install Plugin** window, select the `PyMOL2-parKVFinder-Tools.zip` file you downloaded earliar.
- In the **Select plugin directory** window, select `C:\<user>\anaconda3\envs\pymol\lib\site-packages\pmg_tk\startup` and click **OK**.
- Click **OK** when prompted to confirm the installation.
- Once the **Success** window appears, restart PyMOL.

After restarting, the PyMOL2 parKVFinder Tools should be ready for use.

Please let me know if the error persists, and I’ll be happy to assist further.

**Comment by gaohaohoa** [comment]
Thank you very much for your reply. KVFinder is a very useful tool, and I have completed the relevant work using the web version you provided. I would like to express my gratitude!
